### ISSUE TITLE
what is the difference with json.loads ?

### ISSUE THREAD

**Issue by NargiT** [dalemyers/deserialize#13]
Hello,

I am very interested in your project, but I would like to understand what is the difference between deserialize and `json.loads` when using `object_hook` parameter. https://docs.python.org/3.8/library/json.html#json.loads 

Also does it have to be a json necessary `deserialize.deserialize(MyThing, json_data)` or I can use any string ? 

```python
flat_path: str = "file://path_to_file"
myFile : File = deserialize.deserialize(File, flat_path)
```

I am looking for tool in order to convert any string to a python type (int, float, dict, str, uri, file, custom_format).

Thx

**Comment by dalemyers** [comment]
This tool is a little different than what you've understood I think. It's not meant for turning a string into structured data, but for turning structured data into an object representation. e.g. a dictionary into an object instance. 

You can do this with json by running it through json.loads first, or use XML, or whatever you like. As long as it can be represented at its root level by a dictionary or list this tool can be used to "parse" it. 

Does that make sense?

**Comment by NargiT** [comment]
Understood.

> e.g. a dictionary into an object instance.

May I use a custom data structure and use this lib to turn in into an object representation ?

e.g. 
```
custom_structure: str = "file://path_to_file"
myFile : File = deserialize.deserialize(File, flat_path)
```
or 
```
flat_key_value = a=1;b=2;c=3 # not defined limit 
custom_structure : List[Tuple] = deserialize.deserialize(List[Tuple], flat_key_value)
```

**Comment by dalemyers** [comment]
It doesn't have any kind of heuristics unfortunately (that's far beyond the scope of this tool), so the data already needs to be structured.

**Comment by NargiT** [comment]
and currently only json format are supported.

```python
class Foo:
  def __init__(self):
    self.id= 1023
    self.alias = "Jean"

class Bar:
  def __init__(self):
    self.name = "Jean Pierre"
    self.full = "Popo"

foo = Foo()
bar = Bar()
data = dict()
data[foo] = bar
```


Theoritical json representation
```json
  {
    "id" : 1023,
    "alias" : "Jean"
  } : {
    "name" : "Jean Pierre",
    "full" : "Popo"
  }
```

This is impossible because json does not allow key to be something else than `string`. 

Am I correct?

**Comment by dalemyers** [comment]
You can think of it as JSON if you like, but it's not strictly required. As long as it's a dictionary or list at the root, basically anything is supported (with the exception of some more complex types from the typing module). 

Regarding your representation above, you are correct that it couldn't be represented that way in JSON. It also wouldn't work for this library as it expects the keys to always be strings (as they correspond to variable names).

**Comment by NargiT** [comment]
in my example it's a valid `dict` (__hash__, __eq__ is missing though) just it cannot be created using braces syntaxe. 

> As long as it's a dictionary or list at the root

I think you are confusing json with dictionary syntax. `[]` is not a dictionary. `json` spec on the other hand expect keys to be a string, understand arrays etc... https://www.json.org/ 

`dict` are more flexible and require keys to be immutable  https://docs.python.org/3.6/tutorial/datastructures.html#dictionaries 

```
[...]
dictionaries are indexed by keys, which can be any immutable type; *strings* and *numbers* can always be keys. *Tuples* can be used as keys if they contain only *strings*, *numbers*, or *tuples*; if a tuple contains any mutable object either directly or indirectly, it cannot be used as a key. You can’t use _lists_ as keys, since lists can be modified in place [...]
```

Thanks for the explanation but I believe you should rework the README because this tool is a more powerfull version of json.laods()

Because the example of your README is not the pythonic way.

```python
import json

class MyThing:

  def __init__(self, a, b):
    # worst case type checking is done here
    self.a = a
    self.b = b

  @classmethod
  def from_json(cls, json_data):
    a_value = json_data["a"]
    b_value = json_data["b"]
    return cls(a_value, b_value)

data = """{
  "a": 1,
  "b": 2
}"""

mything = json.loads(data, object_hook=MyThing.from_json)

print(mything.a) # 1
print(mything.b) # 2
print(type(mything.a)) # <class 'int'>
print(type(mything.b)) # <class 'int'>
```

**Comment by dalemyers** [comment]
This library is independent of JSON. You can provide any data you like as long as it's in a dictionary or list at the root. 

You can use the `object_hook` parameter for parsing JSON, that's true, but it's not quite the same as this library for 2 reasons:

1) This library handles more than just JSON
2) This can deal with more complex scenarios than `object_hook` can
