### ISSUE TITLE
Enum support?

### ISSUE THREAD

**Issue by alexandertsema** [dalemyers/deserialize#19]
I haven't found a way to make it deserialize Enums. Am I missing anything or it is not simply supported?

**Comment by dalemyers** [comment]
Enums should work as is out of the box. Can you share an example of what's not working?

**Comment by dalemyers** [comment]
You can see in the enum test case how it is supposed to work: https://github.com/dalemyers/deserialize/blob/2b92d20c526d7e8dee97197d9a37144f9da66dca/tests/test_enums.py

**Comment by alexandertsema** [comment]
my bad, it is working fine

**Comment by dalemyers** [comment]
No problem at all. I am working on better documentation which I'll release at some point and that should make this sort of thing easier.
