### ISSUE TITLE
JSON compatible attribute names (camelCased)

### ISSUE THREAD

**Issue by alexandertsema** [dalemyers/deserialize#21]
Hi there.
Is there any way there can be added another argument  like case_function which can be used to convert camelCase field names from JSON string to snake_case which will be used in  setattr()?

For example if we have class definition like this
```
class Test:
    field_name: int
```
and the JSON string looks like this `'{"fieldName": 0}'`
and `deserialize(Test, json.loads('{"fieldName": 0}'))`
the current implementation will not be able to deserialize: `deserialize.exceptions.DeserializeException: Unexpected missing value for: Test.field_name`

Thanks!

**Comment by dalemyers** [comment]
It's something I plan to do at some point (since that's what most key changes are) but haven't gotten around to it yet. I'll see if I can bump it up in terms of priority. 😊

**Comment by alexandertsema** [comment]
awesome, I can try to put together a PR if it helps :) Right now I have to use a wrapper to preprocess all the keys and it is not super convenient. At the same time I hate marshmallow and the may it's designed.

**Comment by dalemyers** [comment]
I have to admit, I hadn't actually encountered marshmallow before you mentioned it. I looked for alternatives before I created this library, but I guess this one just didn't come up.

That said, it's a bit of a different philosophy than I went for and doesn't look like it would play well with type hints, so I think there's plenty room for both projects. 

I'm hoping to get time to work on this today actually, so let's see how far I get.

**Comment by dalemyers** [comment]
I've pushed a simple implementation to master. Take a look and see what you think.

**Comment by alexandertsema** [comment]
Thanks for getting back to me that fast. If I understood correctly if the class will have attribute set as `setattr(class_reference, "__deserialize_auto_snake__", True)` then the deserializer will pick it up? I just don't use decorators approach, I try to keep classes (contract for svc to svc communication) clean and independent of any dependencies. I guess I will just set the attribute before every deserialize() call.

About marshmallow:  it is good enough if you have a little project you need to get out of the door asap. But unfortunately it has some fundamental design issues. For example explicit dependency between marshmallow and package where you define contracts. If you have a service which depends on 2 different contracts and each contract has different marshmallow versions... I mean you got the point. And many more API design issues. That's why your library is a way cleaner way for deserializing.
I also wrote a serializer and a little wrapper for your library for my projects, I guess I will open source it soonish and maybe we can merge efforts to build something really awesome!

**Comment by alexandertsema** [comment]
when do you think you will be able to push it to pypi?

**Comment by dalemyers** [comment]
You'd just annotate your class with the decorator as normal:

```python
@deserialize.auto_snake()
class MyClass:
    some_integer: int
    some_string: str
```

As for pushing to PyPI, hopefully this morning.

**Comment by dalemyers** [comment]
>I also wrote a serializer and a little wrapper for your library for my projects, I guess I will open source it soonish and maybe we can merge efforts to build something really awesome!

I've got a branch with that locally that I never finished up. Wasn't sure it would be wanted by anyone. Guess I should finish it up!

**Comment by dalemyers** [comment]
Version 1.8.0 was just pushed to PyPI.

**Comment by alexandertsema** [comment]
awesome, thanks a lot!
